### ISSUE TITLE
issue raising workflow

### ISSUE THREAD

**Issue by Sumitwarrior7** [Sumitwarrior7/sample-react-app#10]
When a user selects the "New Issue" button to report an issue, they should be directed to a dedicated page that presents the following options:-
Type of Issue:
1) Bug
2) Improvement
3) Feature

Upon selecting one of these options, the user will be automatically redirected to the corresponding issue page. This page will provide a pre-defined boilerplate template for the issue at hand, which the contributor must utilize. The boilerplate template should include the following fields:
1) Type of Issue
1) Brief Issue Description
2) Optional Relevant Images
Feel free to include any additional information if necessary.

This standardized boilerplate ensures consistency and completeness in issue reporting and allows contributors to customize it according to the specific details of the issue they are addressing.

**Comment by Junaid-Mohamed** [comment]
I would like to work on this, and would start this work today EOD.

**Comment by Sumitwarrior7** [comment]
add comments where necessary in the yaml file

**Comment by Junaid-Mohamed** [comment]
Hi @Sumitwarrior7 , is this issue resolved? since a PR was made and was merged I thought this is solved? if it's not solved? please let me know what is that your looking for?

**Comment by Sumitwarrior7** [comment]
No, the pr was not correct
So, yeah it is not solved yet

You can work on this issue.

**Comment by Sumitwarrior7** [comment]
if you have any doubts, you can ask

**Comment by Sumitwarrior7** [comment]
let me tell you what is the issue all about

**Comment by Sumitwarrior7** [comment]
when anyone clicks on new issue button:

![Screenshot from 2023-10-28 15-54-04](https://github.com/Sumitwarrior7/sample-react-app/assets/108853577/bfa7eeb8-9f9d-454d-8cb4-3b9bfa731abd)

This type page should be appear after clicking new issue button:

![image](https://github.com/Sumitwarrior7/sample-react-app/assets/108853577/0b52956b-b475-4bb9-9d5b-dfb839754362)
Instead use bug, improvement, feature

now, suppose you click on bug , so use should be prompted to another page which contains a general template which looks something like that:

![Screenshot from 2023-10-28 15-57-35](https://github.com/Sumitwarrior7/sample-react-app/assets/108853577/89a097fb-7859-473d-b3bc-88cad3e13f2c)

Dont just copy everything . Take inspiration from the images, build your own including the fields specified above
Also ensure you write proper comments on relevant part of code
