### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by Sumitwarrior7** [Sumitwarrior7/sample-react-app#6]

**Comment by Deepakktripathy** [comment]
Hi, can you please specify as to what is to be updated in the readme file?

**Comment by Sumitwarrior7** [comment]
remove everything from the readme.md and write just the Sample React App

**Comment by Deepakktripathy** [comment]
Ok, so just to be clear, you want the readme file to be completely empty but contain the heading Sample React App, right?

**Comment by Sumitwarrior7** [comment]
yes
